# https://zap-hosting.com/guides/de/docs/dedicated-linux-cs16/
- name: Ensure required libraries are installed
  ansible.builtin.include_role:
    name: roles/utils/os/packages/installed
  vars:
    utils_os_packages_installed__packages: "{{ games_cs_1_6_server_installed__libraries }}"

- name: Install steamcmd
  ansible.builtin.include_role:
    name: roles/utils/os/packages/steamcmd/installed

- name: Ensure Existence of Service User
  ansible.builtin.include_role:
    name: roles/utils/os/users/service/created
  vars:
    - utils_os_users_service_created__group: "{{ games_cs_1_6_server_installed__group }}"
    - utils_os_users_service_created__user: "{{ games_cs_1_6_server_installed__user }}"

- name: Ensure permissions on target directory
  ansible.builtin.include_role:
    name: roles/utils/os/users/service/directory/permissions/granted
  vars:
    - utils_os_users_service_directory_permissions_granted__user: "{{ games_cs_1_6_server_installed__user }}"
    - utils_os_users_service_directory_permissions_granted__group: "{{ games_cs_1_6_server_installed__group }}"
    - utils_os_users_service_directory_permissions_granted__directories: "{{ games_cs_1_6_server_installed__service_directories }}"

- name: Install CS 1.6 Dedicated Server
  ansible.builtin.include_role:
    name: roles/utils/os/packages/steamcmd/app/installed
  vars:
    - utils_os_packages_steamcmd_app_installed__dest: "/games/cs1_6/"

- name: Ensure Environment Variables are properly set
  ansible.builtin.include_role:
    name: roles/utils/os/users/service/environment/variables/persisted
  vars:
    - utils_os_users_service_environment_variables_persisted__user: "{{ games_cs_1_6_server_installed__user }}"
    - utils_os_users_service_environment_variables_persisted__group: "{{ games_cs_1_6_server_installed__group }}"
    - utils_os_users_service_environment_variables_persisted__service_dir: "{{ games_cs_1_6_server_installed__directory }}"
    - utils_os_users_service_environment_variables_persisted__service_lib_subdir: "{{ games_cs_1_6_server_installed__lib_subdir }}"

- name: Perform actions as root
  become: true
  become_user: root
  block:
    - name: Ensure Symlinks
      ansible.builtin.file:
        src: "{{ item.orig }}"
        path: "{{ item.link }}"
        state: link
        force: true
        owner: "{{ games_cs_1_6_server_installed__user }}"
        group: "{{ games_cs_1_6_server_installed__group }}"
      loop: "{{ games_cs_1_6_server_installed__symlinks }}"

- name: Enforce server.cfg template
  ansible.builtin.include_role:
    name: roles/utils/os/file/template/enforced
  vars:
    utils_os_file_template_enforced__directory: "{{ games_cs_1_6_server_installed__cstrike_dir }}"
    utils_os_file_template_enforced__file_name: "server.cfg"
    utils_os_file_template_enforced__user: "{{ games_cs_1_6_server_installed__user }}"
    utils_os_file_template_enforced__group: "{{ games_cs_1_6_server_installed__group }}"

- name: Enforce systemd Service file
  ansible.builtin.include_role:
    name: roles/utils/os/systemd/service/configured
  vars:
    utils_os_systemd_service_configured__user: "{{ games_cs_1_6_server_installed__user }}"
    utils_os_systemd_service_configured__group: "{{ games_cs_1_6_server_installed__group }}"
    utils_os_systemd_service_configured__service_name: "{{ games_cs_1_6_server_installed__service_name }}"
    utils_os_systemd_service_configured__service_description: "{{ games_cs_1_6_server_installed__service_description }}"
    utils_os_systemd_service_configured__working_directory: "{{ games_cs_1_6_server_installed__directory }}"
    utils_os_systemd_service_configured__ld_library_path_string: "{{ games_cs_1_6_server_installed__ld_library_path_string }}"
    utils_os_systemd_service_configured__execstart: "{{ games_cs_1_6_server_installed__execstart }}"