- name: Perform as root
  become: true
  become_user: root
  block:
    - name: Ensure loopback localhost is in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1\s+'
        line: '127.0.0.1   localhost'
        state: present

    - name: Configure 127.0.1.1 with FQDN and short name
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1\s+'
        line: "127.0.1.1 {{ os_network_hosts_set__short_fqhn }} {{ os_network_hosts_set__short_hostname }}"
        state: present

    - name: Map public IP to FQDN and short name in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^92\.42\.45\.192\s+'
        line: "{{  }} {{ os_network_hosts_set__short_fqhn }} {{ os_network_hosts_set__short_hostname }}"
        state: present