# This playbook is used to install a Call of Duty 2 v1.3 Server on Linux (Debian / Ubuntu)

## How to use
# Test SSH connectivity before running the playbook:
# cd ~/ansible
# ansible -i inventory/inventory.yml -k -u root all -m ping
# Enter SSH root password...
# Execute the playbook:
# cd ~/ansible
# ansible-playbook -i inventory/inventory.yml --ask-vault-pass operations/games/cod2/server/install_libcod.yml
- hosts: all
  vars_files:
    - /home/dafrk/ansible/secrets/secrets.yml  # Explicitly include the vault file
  vars:
    ansible_become_pass: "{{ dafrk__local_password }}"
    ansible_port: "{{ dafrk__os.ssh.port | default(27001) }}"
  roles:
    - roles/games/cod2/server/libcod_installed