games_cod1_server_serial_check_disabled__cd_check: "{{ cd_check | default(true, true) }}"
games_cod1_server_serial_check_disabled__port: "{{ dafrk__cod_server.instance_no_1.port if cd_check | default(true) else dafrk__cod_server.instance_no_2.port }}"
