# This Playbook is used to install a CS 1.6 Server
# Test SSH connectivity before running the playbook:
# cd ~/ansible
# ansible -i inventory/inventory.yml -k -u root all -m ping
# Enter SSH root password...
# Execute the playbook:
# cd ~/ansible
# ansible-playbook -i inventory/inventory.yml --ask-vault-pass operations/games/cs/1_6/server/install.yml
- hosts: all
  vars_files:
    - /home/dafrk/ansible/secrets/secrets.yml  # Explicitly include the vault file
  vars:
    ansible_become_pass: "{{ dafrk__local_password }}"
    ansible_port: "{{ dafrk__os.ssh.port | default(27001) }}"
    app_name: cs_server
    is_steam_game: true
  roles:
    - roles/games/cs/1_6/server/installed