# This Playbook is used to install a Half Life 2 Deathmatch Server
# Test SSH connectivity before running the playbook:
# cd ~/ansible
# ansible -i inventory/inventory.yml -k -u root all -m ping
# Enter SSH root password...
# Execute the playbook:
# cd ~/ansible
# ansible-playbook -i inventory/inventory.yml --ask-vault-pass operations/games/half_life/2/server/install.yml
- hosts: all
  vars_files:
    - /home/dafrk/ansible/secrets/secrets.yml  # Explicitly include the vault file
  vars:
    ansible_become_pass: "{{ dafrk__local_password }}"
    ansible_port: "{{ dafrk__os.ssh.port | default(27001) }}"
    app_name: hl2_server
    is_steam_game: true
  roles:
    - roles/games/half_life/2/server/installed